name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build static file
        run: npm run build
        env:
          REACT_APP_DISPLAY_VALUE: ${{ secrets.DISPLAY_VALUE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
    
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://react-ci
